imports:
    - { resource: parameters.yml }

framework:
    secret: %secret%
    assets: ~
    templating:
        engines: ['twig']

# Doctrine Configuration
doctrine:
    dbal:
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
